version: "3"
services:
  # nginx_app:
  #   container_name: nginx_app
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     _ 80:80
  #   restart: always
  #   links:
  #     _ react_app

  react_app:
    container_name: react_app
    build:
      context: ./
      dockerfile: Dockerfile
    # command: npm start
    restart: always
    # expose:
    #   _ 3000
    # ports:
    #   _ 3000:3000
    ports:
      - 80:80
    links:
      - node_app

  node_app:
    container_name: node_app
    build:
      context: ./server
      dockerfile: Dockerfile
    command: npm start
    restart: always
    expose:
      - 3001
    ports:
      - 3001:3001
    links:
      - mongo_db

  mongo_db:
    container_name: mongo_db
    image: mongo
    volumes:
      - mongo_volume:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017

volumes:
  mongo_volume:
